BEGIN_PARALLEL_ACTIONS
Set Sun 0 0 0
Set Sun.Merkury 40 0 0
Set Sun.Wenus 10 0 0
Set Sun.Ziemia 13 0 0
Set Sun.Mars 24 0 0
Set Sun.Jowisz 6 0 0
Set Sun.Saturn 11 0 0
Set Sun.Uran 18 0 0
Set Sun.Neptun 20 0 0
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Pause 1000
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Rotate Sun.Merkury 40
Move Sun.Merkury 1 1
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Rotate Sun.Wenus 80
Move Sun.Wenus 2 2
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Rotate Sun.Ziemia 120
Move Sun.Ziemia 3 3
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Rotate Sun.Mars 160
Move Sun.Mars 4 4
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Rotate Sun.Jowisz 200
Move Sun.Jowisz 5 5
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Rotate Sun.Saturn 240
Move Sun.Saturn 6 6
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Rotate Sun.Uran 280
Move Sun.Uran 7 7
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Rotate Sun.Neptun 320
Move Sun.Neptun 8 8
END_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Pause 2000
BEGIN_PARALLEL_ACTIONS
BEGIN_PARALLEL_ACTIONS
Rotate Sun 360
END_PARALLEL_ACTIONS